Repository sstsimulator/sst-core, pull requests merged in 2020-04, with the labels that each got.

#516 Update Python3 checks to enable specifying a precise version
  config/sst_check_python.m4
  configure.ac
Labels: Enhancement

#522 Python updates
  src/sst/core/configGraph.cc
  src/sst/core/configGraph.h
  src/sst/core/model/python2/pymodel_comp.cc
  src/sst/core/model/python3/pymodel_comp.cc
Labels: Bug, Enhancement

#523 Check for missing python library path and manually fix
  config/sst_check_python.m4
Labels: Bug
