Repository sstsimulator/sst-core, pull requests merged in 2020-03, with the labels that each got.

#497 Split IPC tunnel into defintion and management to enable Pin3
  src/sst/core/Makefile.am
  src/sst/core/interprocess/mmapchild_pin3.h
  src/sst/core/interprocess/mmapparent.cc
  src/sst/core/interprocess/mmapparent.h
  src/sst/core/interprocess/shmchild.h
  src/sst/core/interprocess/shmparent.cc
  src/sst/core/interprocess/shmparent.h
  src/sst/core/interprocess/tunneldef.h
Labels: Enhancement

#499 Add missing includes
  src/sst/core/interprocess/circularBuffer.h
  src/sst/core/interprocess/ipctunnel.h
  src/sst/core/interprocess/mmapparent.h
  src/sst/core/interprocess/shmchild.h
  src/sst/core/interprocess/shmparent.h
  src/sst/core/interprocess/tunneldef.h
Labels: Bug

#486 Stats generalizations: #398 #400 #401
  src/sst/core/baseComponent.cc
  src/sst/core/componentInfo.h
  src/sst/core/statapi/stataccumulator.h
  src/sst/core/statapi/statbase.cc
  src/sst/core/statapi/statbase.h
  src/sst/core/statapi/statengine.cc
  src/sst/core/statapi/statengine.h
  src/sst/core/statapi/stathistogram.h
  src/sst/core/statapi/statnull.h
  src/sst/core/statapi/statoutput.cc
  src/sst/core/statapi/statoutput.h
  src/sst/core/statapi/statoutputconsole.cc
  src/sst/core/statapi/statoutputconsole.h
  src/sst/core/statapi/statoutputcsv.cc
  src/sst/core/statapi/statoutputcsv.h
  src/sst/core/statapi/statoutputhdf5.cc
  src/sst/core/statapi/statoutputhdf5.h
  src/sst/core/statapi/statoutputjson.cc
  src/sst/core/statapi/statoutputjson.h
  src/sst/core/statapi/statoutputtxt.cc
  src/sst/core/statapi/statoutputtxt.h
  src/sst/core/statapi/statuniquecount.h
Labels: AT: WIP
