Repository sstsimulator/sst-core, pull requests merged in 2020-01, with the labels that each got.

#478 Fixes for issue #477
  src/sst/core/link.cc
  src/sst/core/link.h
Labels: Bug, Enhancement

#481 Add registerClock function that takes a timeconverter
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
Labels: Enhancement

#476 Python3
  config/sst_check_python.m4
  src/sst/core/Makefile.am
  src/sst/core/elemLoader.cc
  src/sst/core/main.cc
  src/sst/core/model/Makefile.inc
  src/sst/core/model/element_python.cc
  src/sst/core/model/element_python.h
  src/sst/core/model/python2/pymodel.cc
  src/sst/core/model/python2/pymodel.h
  src/sst/core/model/python2/pymodel_comp.cc
  src/sst/core/model/python2/pymodel_comp.h
  src/sst/core/model/python2/pymodel_link.cc
  src/sst/core/model/python2/pymodel_link.h
  src/sst/core/model/python2/pymodel_statgroup.cc
  src/sst/core/model/python2/pymodel_statgroup.h
  src/sst/core/model/python3/pymodel.cc
  src/sst/core/model/python3/pymodel.h
  src/sst/core/model/python3/pymodel_comp.cc
  src/sst/core/model/python3/pymodel_comp.h
  src/sst/core/model/python3/pymodel_link.cc
  src/sst/core/model/python3/pymodel_link.h
  src/sst/core/model/python3/pymodel_statgroup.cc
  src/sst/core/model/python3/pymodel_statgroup.h
  src/sst/sst.conf
Labels: Enhancement

#415 Update GNU artifacts
  CONTRIBUTING.md
Labels: Documentation, SST-Core
