Repository sstsimulator/sst-core, pull requests merged in 2021-12, with the labels that each got.

#765 Config and Param clean up
  src/sst/core/baseComponent.h
  src/sst/core/cfgoutput/dotConfigOutput.cc
  src/sst/core/cfgoutput/jsonConfigOutput.cc
  src/sst/core/cfgoutput/pythonConfigOutput.cc
  src/sst/core/component.h
  src/sst/core/config.cc
  src/sst/core/config.h
  src/sst/core/configGraph.h
  src/sst/core/configGraphOutput.h
  src/sst/core/main.cc
  src/sst/core/model/json/jsonmodel.cc
  src/sst/core/model/python/pymodel.cc
  src/sst/core/model/python/pymodel.h
  src/sst/core/model/sstmodel.cc
  src/sst/core/model/sstmodel.h
  src/sst/core/params.cc
  src/sst/core/params.h
  src/sst/core/simulation.cc
Labels: AT: CLANG-FORMAT PASS

#767 Added ability to have maps and sets as params
  src/sst/core/config.cc
  src/sst/core/configGraph.h
  src/sst/core/params.cc
  src/sst/core/params.h
  src/sst/core/testElements/coreTest_ParamComponent.cc
  tests/Makefile.inc
  tests/refFiles/test_ParamComponent.out
  tests/test_ParamComponent.py
  tests/testsuite_default_ParamComponent.py
Labels: Enhancement, AT: CLANG-FORMAT PASS

#768 New perf manual rebase
  config/sst_enable_perf_tracking.m4
  configure.ac
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/clock.cc
  src/sst/core/event.cc
  src/sst/core/event.h
  src/sst/core/simulation.cc
  src/sst/core/simulation_impl.h
  src/sst/core/sync/rankSyncParallelSkip.cc
  src/sst/core/sync/rankSyncSerialSkip.cc
  src/sst/core/sync/syncManager.cc
  src/sst/core/sync/syncQueue.cc
  src/sst/core/testElements/Makefile.inc
  src/sst/core/testElements/coreTest_PerfComponent.cc
  src/sst/core/testElements/coreTest_PerfComponent.h
  tests/Makefile.inc
  tests/refFiles/test_PerfComponent.out
  tests/test_PerfComponent.py
  tests/testsuite_default_PerfComponent.py
Labels: AT: CLANG-FORMAT PASS

#771 Json fix
  src/sst/core/main.cc
  src/sst/core/model/json/jsonmodel.cc
  src/sst/core/threadsafe.h
  tests/testsuite_default_config_input_output.py
Labels: Bug, AT: CLANG-FORMAT PASS

#773 Added missing cc file
  src/sst/core/testElements/CMakeLists.txt
Labels: Bug, SST-Core, SST-BuildSystem, AT: CLANG-FORMAT PASS
