Repository sstsimulator/sst-core, pull requests merged in 2021-04, with the labels that each got.

#605 Fix issue with wrong reported simulated time in some corner cases
  src/sst/core/baseComponent.h
  src/sst/core/exit.cc
  src/sst/core/exit.h
  src/sst/core/main.cc
  src/sst/core/simulation.cc
  src/sst/core/simulation.h
Labels: Bug

#607 Cleanup some build warnings
  src/sst/core/config.cc
  src/sst/core/testElements/Makefile.inc
  src/sst/core/testElements/coreTest_ClockerComponent.cc
  src/sst/core/testElements/coreTest_SharedObjectComponent.cc
Labels: SST-Core

#613 Bug fixes and memory/exection time optimizations for large graphs.
  src/sst/core/baseComponent.h
  src/sst/core/cfgoutput/dotConfigOutput.cc
  src/sst/core/cfgoutput/dotConfigOutput.h
  src/sst/core/cfgoutput/jsonConfigOutput.cc
  src/sst/core/cfgoutput/jsonConfigOutput.h
  src/sst/core/cfgoutput/pythonConfigOutput.cc
  src/sst/core/cfgoutput/pythonConfigOutput.h
  src/sst/core/cfgoutput/xmlConfigOutput.cc
  src/sst/core/cfgoutput/xmlConfigOutput.h
  src/sst/core/componentInfo.cc
  src/sst/core/componentInfo.h
  src/sst/core/configGraph.cc
  src/sst/core/configGraph.h
  src/sst/core/impl/partitioners/linpart.cc
  src/sst/core/impl/partitioners/rrobin.cc
  src/sst/core/impl/partitioners/simplepart.cc
  src/sst/core/impl/partitioners/singlepart.cc
  src/sst/core/impl/partitioners/zoltpart.cc
  src/sst/core/main.cc
  src/sst/core/memuse.cc
  src/sst/core/memuse.h
  src/sst/core/model/python/pymodel.cc
  src/sst/core/model/python/pymodel.h
  src/sst/core/model/python/pymodel_comp.cc
  src/sst/core/model/python/pymodel_stat.cc
  src/sst/core/objectComms.h
  src/sst/core/params.cc
  src/sst/core/params.h
  src/sst/core/simulation.cc
  src/sst/core/sparseVectorMap.h
  src/sst/core/testElements/coreTest_ParamComponent.cc
  src/sst/core/testElements/coreTest_ParamComponent.h
  tests/test_ParamComponent.py
Labels: Bug, Enhancement

#614 More sst11 cleanup
  src/sst/core/configGraph.cc
  src/sst/core/params.cc
Labels: Bug

#616 Fixed bug in SharedArray when not all instances set the size
  src/sst/core/shared/sharedArray.h
  src/sst/core/shared/sharedMap.h
  src/sst/core/shared/sharedObject.h
  src/sst/core/shared/sharedSet.h
  src/sst/core/testElements/coreTest_SharedObjectComponent.cc
Labels: Bug

#618 New experimental StandardMem interface
  src/sst/core/Makefile.am
  src/sst/core/interfaces/stdMem.cc
  src/sst/core/interfaces/stdMem.h
Labels: Enhancement, SST-Core
