Repository sstsimulator/sst-core, pull requests merged in 2022-01, with the labels that each got.

#775 TestFrameworks addtions
  src/sst/core/testingframework/sst_unittest.py
  src/sst/core/testingframework/sst_unittest_support.py
Labels: Enhancement, SST-Test Frameworks, AT: CLANG-FORMAT PASS

#776 Global param ordering fix
  src/sst/core/config.cc
  src/sst/core/config.h
  src/sst/core/main.cc
  src/sst/core/params.cc
  src/sst/core/testElements/coreTest_ParamComponent.cc
  tests/refFiles/test_ParamComponent.out
  tests/test_ParamComponent.py
Labels: Bug, AT: CLANG-FORMAT PASS

#778 Outputting empty components and links for ranks that do not have components and/or links
  src/sst/core/cfgoutput/jsonConfigOutput.cc
Labels: AT: CLANG-FORMAT PASS

#779 Improved the error message printed when a library fails to load.
  src/sst/core/elemLoader.cc
Labels: Enhancement, AT: CLANG-FORMAT PASS

#780 Fixed build when --disable-mpi is used in configure
  src/sst/core/main.cc
Labels: AT: CLANG-FORMAT PASS

#782 Replace shell command with native python for diffing files
  src/sst/core/testElements/coreTest_ParamComponent.h
  src/sst/core/testingframework/sst_unittest_support.py
  tests/refFiles/test_ParamComponent.out
  tests/testsuite_default_ParamComponent.py
Labels: SST-Test Frameworks, AT: CLANG-FORMAT PASS

#783 Added checks for valid names for links and components.
  src/sst/core/configGraph.cc
  src/sst/core/configGraph.h
  src/sst/core/testingframework/sst_unittest_support.py
  tests/refFiles/test_ParamComponent.out
  tests/test_Component.py
  tests/test_MessageMesh.py
  tests/test_ParamComponent.py
  tests/test_PerfComponent.py
Labels: AT: CLANG-FORMAT PASS

#787 Added param, port and slot name checking.
  src/sst/core/Makefile.am
  src/sst/core/configGraph.cc
  src/sst/core/elemLoader.cc
  src/sst/core/namecheck.cc
  src/sst/core/namecheck.h
  src/sst/core/testElements/coreTest_ParamComponent.cc
  src/sst/core/testElements/coreTest_ParamComponent.h
  tests/refFiles/test_ParamComponent.out
  tests/test_ParamComponent.py
Labels: AT: CLANG-FORMAT PASS

#791 Streamlining the interface to Perf counters by removing redundant registerClockHandler call
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/testElements/coreTest_PerfComponent.cc
  tests/testsuite_default_PerfComponent.py
Labels: AT: CLANG-FORMAT PASS
