Repository sstsimulator/sst-core, pull requests merged in 2022-04, with the labels that each got.

#818 Deprecated Simulation::getSimulation()
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/configGraph.cc
  src/sst/core/event.cc
  src/sst/core/exit.cc
  src/sst/core/factory.cc
  src/sst/core/link.cc
  src/sst/core/model/element_python.cc
  src/sst/core/oneshot.cc
  src/sst/core/shared/sharedArray.h
  src/sst/core/shared/sharedMap.h
  src/sst/core/shared/sharedObject.cc
  src/sst/core/shared/sharedObject.h
  src/sst/core/shared/sharedSet.h
  src/sst/core/simulation.cc
  src/sst/core/simulation.h
  src/sst/core/simulation_impl.h
  src/sst/core/statapi/statfieldinfo.cc
  src/sst/core/statapi/statoutput.cc
  src/sst/core/statapi/statoutputcsv.cc
  src/sst/core/statapi/statoutputjson.cc
  src/sst/core/statapi/statoutputtxt.cc
  src/sst/core/testElements/coreTest_Component.cc
  src/sst/core/testElements/coreTest_Links.cc
  src/sst/core/testElements/coreTest_ParamComponent.cc
  src/sst/core/testElements/coreTest_PerfComponent.cc
  src/sst/core/testElements/coreTest_StatisticsComponent.cc
Labels: AT: CLANG-FORMAT PASS

#821 Remove deprecated features
  src/sst/core/Makefile.am
  src/sst/core/config.cc
  src/sst/core/config.h
  src/sst/core/main.cc
  src/sst/core/objectComms.h
  src/sst/core/objectSerialization.h
  src/sst/core/testElements/README
  src/sst/core/testElements/coreTest_Serialization.cc
  tests/Makefile.inc
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_2l.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_2n.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_2n2l.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_2n2n.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_2nl.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_2nn.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_l.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_n.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_n2l.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_n2n.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_nl.out
  tests/subcomponent_tests/legacy/refFiles/test_sc_legacy_nn.out
  tests/subcomponent_tests/legacy/test_sc_legacy_2l.py
  tests/subcomponent_tests/legacy/test_sc_legacy_2n.py
  tests/subcomponent_tests/legacy/test_sc_legacy_2n2l.py
  tests/subcomponent_tests/legacy/test_sc_legacy_2n2n.py
  tests/subcomponent_tests/legacy/test_sc_legacy_2nl.py
  tests/subcomponent_tests/legacy/test_sc_legacy_2nn.py
  tests/subcomponent_tests/legacy/test_sc_legacy_l.py
  tests/subcomponent_tests/legacy/test_sc_legacy_n.py
  tests/subcomponent_tests/legacy/test_sc_legacy_n2l.py
  tests/subcomponent_tests/legacy/test_sc_legacy_n2n.py
  tests/subcomponent_tests/legacy/test_sc_legacy_nl.py
  tests/subcomponent_tests/legacy/test_sc_legacy_nn.py
Labels: AT: CLANG-FORMAT PASS

#824 Testing: Add artifact saving to gitlabCI job
  experimental/.gitlab-ci.yml
Labels: SST-Core, AT: CLANG-FORMAT PASS

#826 Recurse subcomponents
  src/sst/core/cfgoutput/dotConfigOutput.cc
  src/sst/core/cfgoutput/dotConfigOutput.h
Labels: AT: CLANG-FORMAT PASS

#828 Large core timebase
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/event.h
  src/sst/core/exit.cc
  src/sst/core/exit.h
  src/sst/core/simulation.cc
  src/sst/core/timeLord.cc
Labels: Bug, AT: CLANG-FORMAT PASS

#830 Deprecation cleanup
  src/sst/core/baseComponent.h
  src/sst/core/event.cc
  src/sst/core/event.h
  src/sst/core/link.cc
  src/sst/core/link.h
  src/sst/core/module.h
  src/sst/core/testElements/coreTest_Module.h
Labels: AT: CLANG-FORMAT PASS

#832 Remove use of sprintf
  src/sst/core/Makefile.am
  src/sst/core/baseComponent.cc
  src/sst/core/bootshared.cc
  src/sst/core/cfgoutput/pythonConfigOutput.cc
  src/sst/core/elemLoader.cc
  src/sst/core/env/envquery.cc
  src/sst/core/heartbeat.cc
  src/sst/core/main.cc
  src/sst/core/model/python/pymodel.cc
  src/sst/core/model/python/pymodel_comp.cc
  src/sst/core/output.cc
  src/sst/core/rng/marsaglia.h
  src/sst/core/rng/mersenne.h
  src/sst/core/rng/sstrng.h
  src/sst/core/rng/xorshift.h
  src/sst/core/simulation.cc
  src/sst/core/sstregistertool.cc
  src/sst/core/statapi/statfieldinfo.cc
  src/sst/core/statapi/statoutputcsv.cc
  src/sst/core/statapi/statoutputtxt.cc
  src/sst/core/stringize.cc
  src/sst/core/stringize.h
  src/sst/core/testElements/coreTest_DistribComponent.cc
  src/sst/core/testElements/coreTest_LookupTableComponent.cc
  src/sst/core/testElements/coreTest_RNGComponent.h
  src/sst/core/testElements/coreTest_StatisticsComponent.h
Labels: AT: CLANG-FORMAT PASS
