Repository sstsimulator/sst-core, pull requests merged in 2022-02, with the labels that each got.

#792 Tweaked ConfigGraph data structure and added splitGraph()
  src/sst/core/cfgoutput/dotConfigOutput.cc
  src/sst/core/cfgoutput/dotConfigOutput.h
  src/sst/core/cfgoutput/jsonConfigOutput.cc
  src/sst/core/cfgoutput/pythonConfigOutput.cc
  src/sst/core/cfgoutput/xmlConfigOutput.cc
  src/sst/core/cfgoutput/xmlConfigOutput.h
  src/sst/core/configGraph.cc
  src/sst/core/configGraph.h
  src/sst/core/main.cc
  src/sst/core/simulation.cc
  src/sst/core/sparseVectorMap.h
Labels: Enhancement, AT: CLANG-FORMAT PASS

#795 Changed how activities get ordered based on the links they're sent on.
  src/sst/core/action.h
  src/sst/core/activity.h
  src/sst/core/componentInfo.cc
  src/sst/core/componentInfo.h
  src/sst/core/configGraph.cc
  src/sst/core/configGraph.h
  src/sst/core/event.h
  src/sst/core/link.cc
  src/sst/core/link.h
  src/sst/core/linkPair.h
  src/sst/core/simulation.cc
  src/sst/core/sync/rankSyncParallelSkip.cc
  src/sst/core/sync/rankSyncParallelSkip.h
  src/sst/core/sync/rankSyncSerialSkip.cc
  src/sst/core/sync/rankSyncSerialSkip.h
  src/sst/core/sync/syncManager.cc
  src/sst/core/sync/threadSyncSimpleSkip.cc
Labels: AT: CLANG-FORMAT PASS

#797 Renaming top level info files to be .md files
  INSTALL.md
  ISSUES.md
  LICENSE.md
  Makefile.am
  PLATFORMS.md
  VERSION.md
Labels: AT: CLANG-FORMAT PASS

#799 Updates to statistics.
  src/sst/core/Makefile.am
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/configGraph.cc
  src/sst/core/configGraph.h
  src/sst/core/factory.cc
  src/sst/core/main.cc
  src/sst/core/model/python/pymodel_comp.cc
  src/sst/core/statapi/statbase.cc
  src/sst/core/statapi/statbase.h
  src/sst/core/statapi/statoutputconsole.cc
  src/sst/core/statapi/statoutputconsole.h
  src/sst/core/statapi/statoutputtxt.cc
  src/sst/core/statapi/statoutputtxt.h
  src/sst/core/testElements/coreTest_StatisticsComponent.cc
  src/sst/core/testElements/coreTest_StatisticsComponent.h
  tests/refFiles/test_StatisticsComponent_basic.out
  tests/test_StatisticsComponent.py
  tests/test_StatisticsComponent_basic.py
  tests/testsuite_default_StatisticsComponent.py
Labels: Bug, Enhancement, AT: CLANG-FORMAT PASS

#801 StdMem: Minor fixes
  src/sst/core/interfaces/stdMem.h
Labels: AT: CLANG-FORMAT PASS
