Repository sstsimulator/sst-core, pull requests merged in 2024-10, with the labels that each got.

#1137 deprecate simple host_os_get_* methods
  src/sst/core/testingframework/sst_unittest_support.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1144 Add handling for output file naming conventions in OpenMPI 5.0.x
  src/sst/core/testingframework/sst_unittest_support.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1145 deprecate type-specific configuration getters; add generic replacement functions
  src/sst/core/testingframework/sst_unittest_support.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1143 Make signal handlers user-settable.
  src/sst/core/checkpointAction.cc
  src/sst/core/config.cc
  src/sst/core/config.h
  src/sst/core/configBase.cc
  src/sst/core/configBase.h
  src/sst/core/profile/syncProfileTool.cc
  src/sst/core/simulation.cc
  src/sst/core/simulation_impl.h
  src/sst/core/testElements/coreTest_Component.cc
  src/sst/core/testElements/coreTest_Component.h
  tests/test_RealTime.py
  tests/testsuite_default_RealTime.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1148 make helper function internal
  src/sst/core/testingframework/sst_unittest_support.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1152 Fix call to os.path.isfile()
  src/sst/core/testingframework/sst_unittest_support.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1150 Allow overriding default timeout in os_cmd() calls
  src/sst/core/testingframework/sst_unittest_support.py
  src/sst/core/testingframework/test_engine_support.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1154 Remove calls to deprecated functions
  src/sst/core/testingframework/sst_unittest.py
  src/sst/core/testingframework/sst_unittest_support.py
  src/sst/core/testingframework/test_engine.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1158 Bug fixes for parallel checkpointing.
  src/sst/core/simulation.cc
  src/sst/core/sync/syncManager.cc
  src/sst/core/testElements/coreTest_Component.h
Labels: Bug, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1151 Add initial set of Python type annotations
  pyproject.toml
  scripts/format-diff
  src/sst/core/model/xmlToPython.py
  src/sst/core/testingframework/sst_test_engine_loader.py
  src/sst/core/testingframework/sst_unittest.py
  src/sst/core/testingframework/sst_unittest_parameterized.py
  src/sst/core/testingframework/sst_unittest_support.py
  src/sst/core/testingframework/test_engine.py
  src/sst/core/testingframework/test_engine_globals.py
  src/sst/core/testingframework/test_engine_junit.py
  src/sst/core/testingframework/test_engine_support.py
  src/sst/core/testingframework/test_engine_unittest.py
  tests/testsuite_default_RealTime.py
Labels: SST-Test Frameworks, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1159 Serialization mapping mode and interactive mode
  src/sst/core/Makefile.am
  src/sst/core/activity.h
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/componentInfo.cc
  src/sst/core/componentInfo.h
  src/sst/core/config.cc
  src/sst/core/config.h
  src/sst/core/impl/Makefile.inc
  src/sst/core/impl/interactive/Makefile.inc
  src/sst/core/impl/interactive/simpleDebug.cc
  src/sst/core/impl/interactive/simpleDebug.h
  src/sst/core/interactiveAction.h
  src/sst/core/interactiveConsole.cc
  src/sst/core/interactiveConsole.h
  src/sst/core/interfaces/TestEvent.h
  src/sst/core/interfaces/simpleNetwork.h
  src/sst/core/interfaces/stringEvent.h
  src/sst/core/link.cc
  src/sst/core/link.h
  src/sst/core/main.cc
  src/sst/core/params.cc
  src/sst/core/pollingLinkQueue.cc
  src/sst/core/realtime.cc
  src/sst/core/realtimeAction.h
  src/sst/core/serialization/CMakeLists.txt
  src/sst/core/serialization/impl/CMakeLists.txt
  src/sst/core/serialization/impl/mapper.h
  src/sst/core/serialization/impl/serialize_array.h
  src/sst/core/serialization/impl/serialize_atomic.h
  src/sst/core/serialization/impl/serialize_deque.h
  src/sst/core/serialization/impl/serialize_list.h
  src/sst/core/serialization/impl/serialize_map.h
  src/sst/core/serialization/impl/serialize_multiset.h
  src/sst/core/serialization/impl/serialize_priority_queue.h
  src/sst/core/serialization/impl/serialize_set.h
  src/sst/core/serialization/impl/serialize_string.h
  src/sst/core/serialization/impl/serialize_vector.h
  src/sst/core/serialization/objectMap.cc
  src/sst/core/serialization/objectMap.h
  src/sst/core/serialization/objectMapDeferred.h
  src/sst/core/serialization/serializable.cc
  src/sst/core/serialization/serializable.h
  src/sst/core/serialization/serializable_base.h
  src/sst/core/serialization/serialize.h
  src/sst/core/serialization/serializer.cc
  src/sst/core/serialization/serializer.h
  src/sst/core/shared/sharedArray.h
  src/sst/core/shared/sharedMap.h
  src/sst/core/shared/sharedSet.h
  src/sst/core/simulation.cc
  src/sst/core/simulation_impl.h
  src/sst/core/statapi/statbase.h
  src/sst/core/testElements/coreTest_Serialization.cc
  src/sst/core/testElements/coreTest_SubComponent.cc
  src/sst/core/testElements/coreTest_SubComponent.h
  src/sst/core/timeConverter.h
  src/sst/core/timeLord.cc
  src/sst/core/timeVortex.h
  src/sst/core/unitAlgebra.h
Labels: Enhancement, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS, Major Feature

#1160 Fix test logic for shared array
  src/sst/core/testElements/coreTest_SharedObjectComponent.cc
  src/sst/core/testingframework/sst_unittest_support.py
  tests/testsuite_default_PerfComponent.py
  tests/testsuite_default_StatisticsComponent.py
  tests/testsuite_default_config_input_output.py
  tests/testsuite_default_sstinfo.py
  tests/testsuite_testengine_testing.py
Labels: AT: RETEST, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1162 Fixes uninitialized object segfault in debugger
  src/sst/core/impl/interactive/simpleDebug.cc
  src/sst/core/impl/interactive/simpleDebug.h
  src/sst/core/serialization/objectMap.h
  src/sst/core/simulation.cc
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1168 Header file cleanup for ELI and serialization headers.
  src/sst/core/baseComponent.cc
  src/sst/core/eli/defaultInfo.h
  src/sst/core/eli/elementinfo.cc
  src/sst/core/eli/elementinfo.h
  src/sst/core/eli/interfaceInfo.h
  src/sst/core/eli/paramsInfo.h
  src/sst/core/factory.cc
  src/sst/core/factory.h
  src/sst/core/impl/timevortex/timeVortexBinnedMap.h
  src/sst/core/impl/timevortex/timeVortexPQ.h
  src/sst/core/interactiveConsole.h
  src/sst/core/model/sstmodel.h
  src/sst/core/module.h
  src/sst/core/params.cc
  src/sst/core/params.h
  src/sst/core/profile/clockHandlerProfileTool.cc
  src/sst/core/profile/componentProfileTool.cc
  src/sst/core/profile/eventHandlerProfileTool.cc
  src/sst/core/serialization/objectMap.h
  src/sst/core/sstinfo.cc
  src/sst/core/sstpart.cc
  src/sst/core/statapi/stathistogram.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1171 Fix spelling mistake in test framework method
  src/sst/core/testingframework/test_engine_unittest.py
Labels: SST-Test Frameworks, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS
