Repository sstsimulator/sst-core, pull requests merged in 2024-01, with the labels that each got.

#1021 Add interface for accessing CustomReq/Resp data
  src/sst/core/interfaces/stdMem.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1027 Add SSTConfigVersion.cmake to allow cmake find_package with version
  configure.ac
  share/CMakeLists.txt
  share/Makefile.am
  share/SSTConfigVersion.cmake.in
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1026 Fix compiler error when calling addDataNTimes
  src/sst/core/statapi/statbase.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1029 Time fault
  src/sst/core/config.cc
  src/sst/core/main.cc
  src/sst/core/simulation.cc
  src/sst/core/testElements/coreTest_Component.cc
  src/sst/core/testElements/coreTest_Component.h
  src/sst/core/testingframework/sst_unittest_support.py
  tests/Makefile.inc
  tests/refFiles/test_Component_time_overflow.out
  tests/test_Component_time_overflow.py
  tests/testsuite_default_Component.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1032 Fixed some python issues
  src/sst/core/cfgoutput/pythonConfigOutput.cc
  src/sst/core/cfgoutput/pythonConfigOutput.h
  src/sst/core/model/python/pymodel.cc
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1033 Add interactive SST-info
  config/ax_require_defined.m4
  config/sst_check_curses.m4
  configure.ac
  src/sst/core/Makefile.am
  src/sst/core/sstinfo.cc
  src/sst/core/sstinfo.h
Labels: AT: CLANG-FORMAT PASS, AT: PRE-TEST INSPECTED, AT: CMAKE-FORMAT PASS

#1040 Update CONTRIBUTING.md with more detail and C++17
  CONTRIBUTING.md
Labels: Enhancement, SST-General, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1041 Doxygen Documentation - Small Updates
  src/sst/core/configGraphOutput.h
  src/sst/core/cputimer.h
  src/sst/core/event.h
  src/sst/core/exit.h
  src/sst/core/linkPair.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1043 Use exceptions for UnitAlgebra errors
  src/sst/core/model/python/pymodel_unitalgebra.cc
  src/sst/core/unitAlgebra.cc
  src/sst/core/unitAlgebra.h
  tests/test_UnitAlgebra.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS
