Repository sstsimulator/sst-core, pull requests merged in 2025-02, with the labels that each got.

#1201 Added support for PortModules.
  .clang-format
  src/sst/core/Makefile.am
  src/sst/core/activity.h
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/componentInfo.cc
  src/sst/core/componentInfo.h
  src/sst/core/configGraph.cc
  src/sst/core/configGraph.h
  src/sst/core/event.h
  src/sst/core/impl/Makefile.inc
  src/sst/core/impl/portmodules/Makefile.inc
  src/sst/core/impl/portmodules/randomDrop.cc
  src/sst/core/impl/portmodules/randomDrop.h
  src/sst/core/link.cc
  src/sst/core/link.h
  src/sst/core/model/python/pymodel_comp.cc
  src/sst/core/portModule.cc
  src/sst/core/portModule.h
  src/sst/core/profile/clockHandlerProfileTool.h
  src/sst/core/profile/eventHandlerProfileTool.h
  src/sst/core/profile/syncProfileTool.h
  src/sst/core/serialization/impl/serialize_string.h
  src/sst/core/serialization/serialize.h
  src/sst/core/ssthandler.h
  src/sst/core/testElements/Makefile.inc
  src/sst/core/testElements/coreTest_PortModule.cc
  src/sst/core/testElements/coreTest_PortModule.h
  src/sst/core/testElements/coreTest_Serialization.cc
  src/sst/core/testingframework/sst_unittest_support.py
  tests/Makefile.inc
  tests/refFiles/test_PortModule_drop.out
  tests/refFiles/test_PortModule_modify.out
  tests/refFiles/test_PortModule_pass.out
  tests/refFiles/test_PortModule_randomdrop_recv.out
  tests/refFiles/test_PortModule_randomdrop_send.out
  tests/refFiles/test_PortModule_replace.out
  tests/test_PortModule.py
  tests/testsuite_default_Checkpoint.py
  tests/testsuite_default_Output.py
  tests/testsuite_default_PortModule.py
  tests/testsuite_default_Serialization.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS, Major Feature

#1203 Import Python Coverage
  .clang-format
  src/sst/core/Makefile.am
  src/sst/core/config.cc
  src/sst/core/config.h
  src/sst/core/configBase.cc
  src/sst/core/configBase.h
  src/sst/core/from_string.h
  src/sst/core/model/python/pymodel.cc
  src/sst/core/model/python/pymodel.h
  src/sst/core/model/python/pymodel_comp.cc
  src/sst/core/model/python/pymodel_link.cc
  src/sst/core/model/python/pymodel_stat.cc
  src/sst/core/model/python/pymodel_statgroup.cc
  src/sst/core/model/python/pymodel_unitalgebra.cc
  src/sst/core/util/Makefile.inc
  src/sst/core/util/smartTextFormatter.cc
  src/sst/core/util/smartTextFormatter.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1210 Handle zero-length string in UnitAlgebra::trim()
  src/sst/core/unitAlgebra.cc
Labels: AT: CLANG-FORMAT PASS, AT: PRE-TEST INSPECTED, AT: CMAKE-FORMAT PASS

#1212 Simplify SST_ELI_COMPILED_VERSION
  src/sst/core/eli/elementinfo.cc
  src/sst/core/eli/elibase.cc
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1213 Combine combineEliInfo() implementations
  src/sst/core/eli/elementinfo.cc
  src/sst/core/eli/elibase.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1220 Use _t and _v traits instead of ::type and ::value
  src/sst/core/baseComponent.h
  src/sst/core/decimal_fixedpoint.h
  src/sst/core/eli/attributeInfo.h
  src/sst/core/eli/elementbuilder.h
  src/sst/core/eli/elementinfo.h
  src/sst/core/eli/paramsInfo.h
  src/sst/core/eli/portsInfo.h
  src/sst/core/eli/profilePointInfo.h
  src/sst/core/eli/simpleInfo.h
  src/sst/core/eli/statsInfo.h
  src/sst/core/eli/subcompSlotInfo.h
  src/sst/core/from_string.h
  src/sst/core/impl/timevortex/timeVortexBinnedMap.h
  src/sst/core/impl/timevortex/timeVortexPQ.h
  src/sst/core/params.h
  src/sst/core/serialization/impl/serialize_array.h
  src/sst/core/serialization/serializable.h
  src/sst/core/serialization/serialize.h
  src/sst/core/shared/sharedArray.h
  src/sst/core/shared/sharedMap.h
  src/sst/core/shared/sharedSet.h
  src/sst/core/ssthandler.h
  src/sst/core/statapi/statbase.h
  src/sst/core/statapi/statnull.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1219 Empty (void) parameter lists
  src/sst/core/activity.h
  src/sst/core/baseComponent.h
  src/sst/core/checkpointAction.cc
  src/sst/core/checkpointAction.h
  src/sst/core/clock.cc
  src/sst/core/clock.h
  src/sst/core/configBase.cc
  src/sst/core/configBase.h
  src/sst/core/configShared.cc
  src/sst/core/configShared.h
  src/sst/core/event.cc
  src/sst/core/event.h
  src/sst/core/exit.h
  src/sst/core/heartbeat.cc
  src/sst/core/heartbeat.h
  src/sst/core/interfaces/simpleNetwork.h
  src/sst/core/interfaces/stdMem.h
  src/sst/core/interfaces/stringEvent.h
  src/sst/core/interprocess/ipctunnel.h
  src/sst/core/interprocess/mmapchild_pin3.h
  src/sst/core/interprocess/mmapparent.h
  src/sst/core/interprocess/shmchild.h
  src/sst/core/interprocess/shmparent.h
  src/sst/core/link.cc
  src/sst/core/model/python/pymodel.cc
  src/sst/core/model/python/pymodel.h
  src/sst/core/oneshot.cc
  src/sst/core/oneshot.h
  src/sst/core/serialization/serializer.h
  src/sst/core/simulation.cc
  src/sst/core/simulation_impl.h
  src/sst/core/statapi/statengine.h
  src/sst/core/statapi/statoutputcsv.cc
  src/sst/core/statapi/statoutputjson.cc
  src/sst/core/statapi/statoutputtxt.cc
  src/sst/core/sync/rankSyncSerialSkip.cc
  src/sst/core/sync/syncManager.cc
  src/sst/core/sync/syncManager.h
  src/sst/core/sync/threadSyncDirectSkip.h
  src/sst/core/sync/threadSyncSimpleSkip.h
  src/sst/core/testElements/coreTest_MemPoolTest.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1208 Optimize statistics memory usage
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/componentInfo.cc
  src/sst/core/componentInfo.h
  src/sst/core/configGraph.cc
  src/sst/core/configGraph.h
  src/sst/core/simulation.cc
  src/sst/core/sstinfo.cc
  src/sst/core/statapi/stataccumulator.h
  src/sst/core/statapi/statbase.cc
  src/sst/core/statapi/statbase.h
  src/sst/core/statapi/statengine.cc
  src/sst/core/statapi/statengine.h
  src/sst/core/statapi/statfieldinfo.cc
  src/sst/core/statapi/statfieldinfo.h
  src/sst/core/statapi/statgroup.cc
  src/sst/core/statapi/statgroup.h
  src/sst/core/statapi/stathistogram.h
  src/sst/core/statapi/statnull.h
  src/sst/core/statapi/statoutputtxt.h
  src/sst/core/statapi/statuniquecount.h
  src/sst/core/testElements/coreTest_Checkpoint.cc
  src/sst/core/testElements/coreTest_Checkpoint.h
  src/sst/core/testElements/coreTest_StatisticsComponent.cc
  src/sst/core/testElements/coreTest_StatisticsComponent.h
  tests/refFiles/test_StatisticsComponent_basic.out
  tests/test_StatisticsComponent_basic.py
Labels: Enhancement, SST-Statistics, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1217 Change typedef declarations to modern using aliases
  src/sst/core/clock.h
  src/sst/core/componentInfo.h
  src/sst/core/configGraph.h
  src/sst/core/eli/elementbuilder.h
  src/sst/core/eli/simpleInfo.h
  src/sst/core/event.h
  src/sst/core/impl/timevortex/timeVortexBinnedMap.h
  src/sst/core/impl/timevortex/timeVortexPQ.h
  src/sst/core/interfaces/simpleNetwork.h
  src/sst/core/interfaces/stdMem.h
  src/sst/core/interprocess/ipctunnel.h
  src/sst/core/interprocess/mmapparent.cc
  src/sst/core/interprocess/shmparent.cc
  src/sst/core/interprocess/tunneldef.h
  src/sst/core/model/element_python.h
  src/sst/core/oneshot.h
  src/sst/core/params.h
  src/sst/core/profile.h
  src/sst/core/serialization/impl/serialize_atomic.h
  src/sst/core/serialization/impl/serialize_deque.h
  src/sst/core/serialization/impl/serialize_list.h
  src/sst/core/serialization/impl/serialize_map.h
  src/sst/core/serialization/impl/serialize_multiset.h
  src/sst/core/serialization/impl/serialize_priority_queue.h
  src/sst/core/serialization/impl/serialize_set.h
  src/sst/core/serialization/impl/serialize_vector.h
  src/sst/core/serialization/serializable_base.h
  src/sst/core/serialization/statics.h
  src/sst/core/shared/sharedArray.h
  src/sst/core/shared/sharedMap.h
  src/sst/core/shared/sharedSet.h
  src/sst/core/simulation_impl.h
  src/sst/core/sparseVectorMap.h
  src/sst/core/sst_types.h
  src/sst/core/ssthandler.h
  src/sst/core/sstinfo.h
  src/sst/core/statapi/statbase.h
  src/sst/core/statapi/statengine.h
  src/sst/core/statapi/stathistogram.h
  src/sst/core/statapi/statoutputhdf5.h
  src/sst/core/stringize.h
  src/sst/core/sync/rankSyncParallelSkip.h
  src/sst/core/sync/rankSyncSerialSkip.h
  src/sst/core/testElements/coreTest_ComponentEvent.h
  src/sst/core/threadsafe.h
  src/sst/core/timeLord.h
  src/sst/core/unitAlgebra.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS
