Repository sstsimulator/sst-core, pull requests merged in 2025-04, with the labels that each got.

#1271 Generalize serialize to support more containers in a generalized way, and store mapping name in a stack stored in the serializer
  src/sst/core/Makefile.am
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/from_string.h
  src/sst/core/impl/interactive/simpleDebug.cc
  src/sst/core/link.cc
  src/sst/core/link.h
  src/sst/core/serialization/impl/CMakeLists.txt
  src/sst/core/serialization/impl/packer.h
  src/sst/core/serialization/impl/serialize_adapter.h
  src/sst/core/serialization/impl/serialize_array.h
  src/sst/core/serialization/impl/serialize_atomic.h
  src/sst/core/serialization/impl/serialize_deque.h
  src/sst/core/serialization/impl/serialize_insertable.h
  src/sst/core/serialization/impl/serialize_list.h
  src/sst/core/serialization/impl/serialize_map.h
  src/sst/core/serialization/impl/serialize_multiset.h
  src/sst/core/serialization/impl/serialize_priority_queue.h
  src/sst/core/serialization/impl/serialize_set.h
  src/sst/core/serialization/impl/serialize_string.h
  src/sst/core/serialization/impl/serialize_tuple.h
  src/sst/core/serialization/impl/serialize_utility.h
  src/sst/core/serialization/impl/serialize_vector.h
  src/sst/core/serialization/impl/unpacker.h
  src/sst/core/serialization/objectMap.cc
  src/sst/core/serialization/objectMap.h
  src/sst/core/serialization/objectMapDeferred.h
  src/sst/core/serialization/serializable.cc
  src/sst/core/serialization/serializable.h
  src/sst/core/serialization/serialize.h
  src/sst/core/serialization/serializer.cc
  src/sst/core/serialization/serializer.h
  src/sst/core/statapi/statbase.h
  src/sst/core/testElements/coreTest_Checkpoint.cc
  src/sst/core/testElements/coreTest_Checkpoint.h
  src/sst/core/testElements/coreTest_Component.cc
  src/sst/core/testElements/coreTest_Serialization.cc
  src/sst/core/testElements/coreTest_Serialization.h
  src/sst/core/testElements/coreTest_SharedObjectComponent.cc
  src/sst/core/testElements/coreTest_SubComponent.h
  src/sst/core/timeConverter.h
  src/sst/core/timeLord.cc
  src/sst/core/timeVortex.h
  src/sst/core/unitAlgebra.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1281 Update GitHub Actions runners to Ubuntu 24.04
  .github/workflows/PR_clang-format_test.yml
  .github/workflows/PR_cmake-format_test.yml
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1263 Fix Valgrind memory errors
  src/sst/core/componentInfo.cc
  src/sst/core/configGraph.h
  src/sst/core/model/python/pymodel.cc
  src/sst/core/model/python/pymodel_comp.cc
  src/sst/core/simulation_impl.h
  src/sst/core/testElements/coreTest_Checkpoint.cc
  src/sst/core/testElements/coreTest_Checkpoint.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1231 Allow user to specify seconds-only wall time in either S or Ss format
  src/sst/core/configBase.cc
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1266 Interactive console realtime action
  src/sst/core/config.cc
  src/sst/core/realtime.cc
  src/sst/core/realtime.h
  src/sst/core/realtimeAction.h
  src/sst/core/serialization/objectMap.h
  src/sst/core/simulation.cc
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1260 Inline trivial default constructors and destructors
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/checkpointAction.cc
  src/sst/core/checkpointAction.h
  src/sst/core/component.cc
  src/sst/core/component.h
  src/sst/core/componentExtension.cc
  src/sst/core/componentExtension.h
  src/sst/core/event.cc
  src/sst/core/event.h
  src/sst/core/heartbeat.cc
  src/sst/core/heartbeat.h
  src/sst/core/initQueue.cc
  src/sst/core/initQueue.h
  src/sst/core/interactiveConsole.cc
  src/sst/core/interactiveConsole.h
  src/sst/core/model/python/pymodel_comp.h
  src/sst/core/pollingLinkQueue.cc
  src/sst/core/pollingLinkQueue.h
  src/sst/core/portModule.cc
  src/sst/core/portModule.h
  src/sst/core/realtime.cc
  src/sst/core/realtimeAction.h
  src/sst/core/sstinfo.cc
  src/sst/core/sstinfo.h
  src/sst/core/statapi/statoutput.cc
  src/sst/core/statapi/statoutput.h
  src/sst/core/subcomponent.cc
  src/sst/core/subcomponent.h
  src/sst/core/sync/syncManager.cc
  src/sst/core/sync/syncManager.h
  src/sst/core/sync/syncQueue.cc
  src/sst/core/sync/syncQueue.h
  src/sst/core/testElements/coreTest_Checkpoint.h
  src/sst/core/testElements/coreTest_Component.cc
  src/sst/core/testElements/coreTest_Component.h
  src/sst/core/testElements/coreTest_Links.cc
  src/sst/core/testElements/coreTest_Links.h
  src/sst/core/testElements/coreTest_Module.cc
  src/sst/core/testElements/coreTest_Module.h
  src/sst/core/uninitializedQueue.cc
  src/sst/core/uninitializedQueue.h
  src/sst/core/unitAlgebra.cc
  src/sst/core/unitAlgebra.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1283 Fix Checkpoint tests for larger partition counts.
  tests/testsuite_default_Checkpoint.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1285 Use .clear() and .reserve() when unpacking containers; handle maps with simple keys which can be converted to string
  src/sst/core/serialization/impl/serialize_insertable.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1284 Migrate OSCommand into public API for sst-test
  src/sst/core/testingframework/sst_unittest.py
  src/sst/core/testingframework/sst_unittest_support.py
  src/sst/core/testingframework/test_engine.py
  src/sst/core/testingframework/test_engine_support.py
  tests/testsuite_default_sstinfo.py
  tests/testsuite_testengine_testing.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1286 adding shared stats writing from JSON; Fix for JSON portion of Issue #1240
  src/sst/core/cfgoutput/jsonConfigOutput.cc
  src/sst/core/cfgoutput/jsonConfigOutput.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1282 Replace incorrect usage of std::is_fundamental with std::is_arithmetic
  src/sst/core/from_string.h
  src/sst/core/serialization/impl/serialize_array.h
  src/sst/core/serialization/serialize.h
  src/sst/core/statapi/statbase.h
  src/sst/core/statapi/statnull.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1290 Add testing_check_is_nightly() function
  src/sst/core/testingframework/sst_unittest_support.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1293 Serialize arrays, making the code much simpler and more general
  src/sst/core/Makefile.am
  src/sst/core/serialization/impl/mapper.cc
  src/sst/core/serialization/impl/serialize_array.cc
  src/sst/core/serialization/impl/serialize_array.h
  src/sst/core/serialization/objectMap.h
  src/sst/core/serialization/serialize.h
  src/sst/core/serialization/serializer.cc
  src/sst/core/serialization/serializer.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1291 StandardMem Serialization
  src/sst/core/interfaces/stdMem.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1255 Use std::make_unique() for variable-length arrays instead of array[N] when N is not constant
  configure.ac
  src/sst/core/bootsst.cc
  src/sst/core/bootsstinfo.cc
  src/sst/core/configBase.cc
  src/sst/core/impl/partitioners/simplepart.cc
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1300 Deprecated Handler in favor of Handler2.
  src/sst/core/interfaces/simpleNetwork.h
  src/sst/core/interfaces/stdMem.h
  src/sst/core/oneshot.h
  src/sst/core/ssthandler.h
  src/sst/core/statapi/statbase.cc
  src/sst/core/statapi/statbase.h
  src/sst/core/statapi/statengine.cc
  src/sst/core/testElements/coreTest_ClockerComponent.cc
  src/sst/core/testElements/coreTest_DistribComponent.cc
  src/sst/core/testElements/coreTest_Links.cc
  src/sst/core/testElements/coreTest_MemPoolTest.cc
  src/sst/core/testElements/coreTest_MessageGeneratorComponent.cc
  src/sst/core/testElements/coreTest_PerfComponent.cc
  src/sst/core/testElements/coreTest_RNGComponent.cc
  src/sst/core/testElements/coreTest_StatisticsComponent.cc
  src/sst/core/testElements/message_mesh/enclosingComponent.cc
  src/sst/core/testElements/message_mesh/enclosingComponent.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1302 Fix enum warnings and make SerOption tests uniform
  src/sst/core/serialization/impl/serialize_array.h
  src/sst/core/serialization/impl/serialize_insertable.h
  src/sst/core/serialization/impl/serialize_tuple.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1301 Deprecate use of shared TimeConverter* objects
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/link.cc
  src/sst/core/link.h
  src/sst/core/objectComms.h
  src/sst/core/portModule.cc
  src/sst/core/portModule.h
  src/sst/core/serialization/impl/serialize_adapter.h
  src/sst/core/serialization/impl/serialize_array.h
  src/sst/core/serialization/impl/serialize_atomic.h
  src/sst/core/serialization/impl/serialize_insertable.h
  src/sst/core/serialization/impl/serialize_string.h
  src/sst/core/serialization/impl/serialize_tuple.h
  src/sst/core/serialization/serializable.h
  src/sst/core/serialization/serialize.h
  src/sst/core/simulation.cc
  src/sst/core/simulation_impl.h
  src/sst/core/statapi/statbase.h
  src/sst/core/sync/rankSyncParallelSkip.cc
  src/sst/core/sync/rankSyncSerialSkip.cc
  src/sst/core/testElements/coreTest_Checkpoint.cc
  src/sst/core/testElements/coreTest_Checkpoint.h
  src/sst/core/testElements/coreTest_Serialization.cc
  src/sst/core/timeConverter.h
  src/sst/core/timeLord.cc
  src/sst/core/timeVortex.h
  src/sst/core/unitAlgebra.h
Labels: Enhancement, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1248 Clean up UNUSED() macro
  src/sst/core/eli/categoryInfo.h
  src/sst/core/impl/interactive/simpleDebug.h
  src/sst/core/interfaces/stdMem.h
  src/sst/core/profile/eventHandlerProfileTool.h
  src/sst/core/shared/sharedObject.h
  src/sst/core/sstinfo.h
  src/sst/core/warnmacros.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1261 Add override for virtual functions which are overriden
  .git-blame-ignore-revs
  configure.ac
  src/sst/core/impl/timevortex/timeVortexPQ.cc
  src/sst/core/interfaces/stdMem.h
  src/sst/core/testElements/coreTest_ClockerComponent.h
  src/sst/core/testElements/coreTest_DistribComponent.h
  src/sst/core/testElements/coreTest_Links.h
  src/sst/core/testElements/coreTest_MessageGeneratorComponent.h
  src/sst/core/testElements/coreTest_ParamComponent.h
  src/sst/core/testElements/coreTest_PerfComponent.h
  src/sst/core/testElements/coreTest_RNGComponent.h
  src/sst/core/testElements/coreTest_StatisticsComponent.h
  src/sst/core/testElements/message_mesh/enclosingComponent.h
  src/sst/core/watchPoint.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1306 Change name of GlobalParams to SharedParams for clarity.
  src/sst/core/cfgoutput/jsonConfigOutput.cc
  src/sst/core/cfgoutput/pythonConfigOutput.cc
  src/sst/core/configGraph.cc
  src/sst/core/configGraph.h
  src/sst/core/configGraphOutput.h
  src/sst/core/main.cc
  src/sst/core/model/json/jsonmodel.cc
  src/sst/core/model/json/jsonmodel.h
  src/sst/core/model/python/pymodel.cc
  src/sst/core/model/python/pymodel_comp.cc
  src/sst/core/model/sstmodel.cc
  src/sst/core/params.cc
  src/sst/core/params.h
  tests/refFiles/test_ParamComponent.out
  tests/test_ParamComponent.py
Labels: Enhancement, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1307 Tc updates
  src/sst/core/activity.h
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/componentInfo.cc
  src/sst/core/componentInfo.h
  src/sst/core/link.cc
  src/sst/core/link.h
  src/sst/core/main.cc
  src/sst/core/simulation.cc
  src/sst/core/simulation_impl.h
  src/sst/core/sync/rankSyncParallelSkip.cc
  src/sst/core/sync/rankSyncSerialSkip.cc
  src/sst/core/sync/syncManager.cc
  src/sst/core/sync/syncManager.h
  src/sst/core/timeConverter.h
  src/sst/core/timeLord.cc
  src/sst/core/timeLord.h
  src/sst/core/warnmacros.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1310 TimeConverter fix
  src/sst/core/timeConverter.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1313 Serialize array bug
  src/sst/core/config.cc
  src/sst/core/serialization/impl/serialize_array.h
Labels: Bug, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1314 Bug fix for timeconverter/basecomponent API
  src/sst/core/baseComponent.cc
  src/sst/core/util/filesystem.h
Labels: Bug, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1315 Massage casting to remove warnings on GCC 14
  src/sst/core/serialization/impl/serialize_insertable.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1303 Merge pointer and non-pointer serialize_impl adapter implementations
  src/sst/core/serialization/impl/serialize_adapter.h
  src/sst/core/serialization/impl/serialize_insertable.h
  src/sst/core/serialization/impl/serialize_tuple.h
  src/sst/core/serialization/impl/serialize_utility.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1316 Fix some warnings found in gcc 8.5-14.2
  src/sst/core/action.h
  src/sst/core/baseComponent.cc
  src/sst/core/clock.h
  src/sst/core/event.h
  src/sst/core/interfaces/simpleNetwork.h
  src/sst/core/interfaces/stdMem.h
  src/sst/core/oneshot.h
  src/sst/core/serialization/impl/serialize_insertable.h
  src/sst/core/serialization/objectMap.h
  src/sst/core/ssthandler.h
  src/sst/core/testElements/coreTest_Serialization.cc
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1320 Changed help messages to reflect features that are no longer experime…
  src/sst/core/config.cc
Labels: Bug, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1321 Bump clang-format requirement from v12 to v20
  .github/workflows/PR_clang-format_test.yml
  scripts/clang-format-test.sh
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1324 Update .git-blame-ignore-revs for some recent PRs.
  .git-blame-ignore-revs
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS
