Repository sstsimulator/sst-core, pull requests merged in 2025-03, with the labels that each got.

#1202 Enforce Python type annotations in continuous integration
  .pre-commit-config.yaml
  pyproject.toml
  src/sst/core/testingframework/sst_unittest_support.py
  src/sst/core/testingframework/test_engine_unittest.py
  tests/test_PortModule.py
Labels: SST-Test Frameworks, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1233 Use modern techniques to delete copy constructors and assignment operators
  src/sst/core/checkpointAction.h
  src/sst/core/exit.h
  src/sst/core/factory.h
  src/sst/core/heartbeat.h
  src/sst/core/interactiveConsole.h
  src/sst/core/simulation_impl.h
  src/sst/core/testElements/coreTest_ClockerComponent.h
  src/sst/core/testElements/coreTest_Component.h
  src/sst/core/testElements/coreTest_DistribComponent.h
  src/sst/core/testElements/coreTest_MessageGeneratorComponent.h
  src/sst/core/testElements/coreTest_ParamComponent.h
  src/sst/core/testElements/coreTest_PerfComponent.h
  src/sst/core/testElements/coreTest_PortModule.h
  src/sst/core/testElements/coreTest_RNGComponent.h
  src/sst/core/testElements/coreTest_StatisticsComponent.h
  src/sst/core/timeLord.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1224 Remove compiler warnings; move all MPI stuff into sst_mpi.h
  src/sst/core/Makefile.am
  src/sst/core/checkpointAction.cc
  src/sst/core/config.cc
  src/sst/core/configGraph.h
  src/sst/core/exit.cc
  src/sst/core/heartbeat.cc
  src/sst/core/iouse.cc
  src/sst/core/main.cc
  src/sst/core/memuse.cc
  src/sst/core/model/python/pymodel.cc
  src/sst/core/objectComms.h
  src/sst/core/output.cc
  src/sst/core/realtime.cc
  src/sst/core/serialization/impl/serialize_set.h
  src/sst/core/simulation.cc
  src/sst/core/sst_mpi.h
  src/sst/core/sync/rankSyncParallelSkip.cc
  src/sst/core/sync/rankSyncParallelSkip.h
  src/sst/core/sync/rankSyncSerialSkip.cc
  src/sst/core/sync/syncManager.cc
  src/sst/core/warnmacros.h
Labels: AT: CLANG-FORMAT PASS, AT: PRE-TEST INSPECTED, AT: CMAKE-FORMAT PASS

#1241 Fix clang-format version check
  scripts/clang-format-test.sh
Labels: Bug, AT: CMAKE-FORMAT PASS

#1229 Use std::vector for varying sized buffers
  src/sst/core/simulation.cc
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1222 Use Meyers singletons
  src/sst/core/elemLoader.cc
  src/sst/core/eli/elementbuilder.h
  src/sst/core/eli/elementinfo.h
  src/sst/core/eli/elibase.cc
  src/sst/core/eli/elibase.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1244 fix typos
  src/sst/core/testElements/coreTest_Checkpoint.cc
  src/sst/core/testElements/coreTest_Component.cc
  src/sst/core/testElements/coreTest_Links.cc
  src/sst/core/testElements/coreTest_MessageGeneratorComponent.cc
  src/sst/core/testElements/coreTest_PerfComponent.cc
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1264 Output directory fix
  config/sst_check_filesystem.m4
  configure.ac
  src/sst/core/Makefile.am
  src/sst/core/checkpointAction.cc
  src/sst/core/checkpointAction.h
  src/sst/core/config.cc
  src/sst/core/config.h
  src/sst/core/configGraphOutput.cc
  src/sst/core/configGraphOutput.h
  src/sst/core/main.cc
  src/sst/core/simulation.cc
  src/sst/core/simulation_impl.h
  src/sst/core/statapi/stataccumulator.h
  src/sst/core/statapi/stathistogram.h
  src/sst/core/statapi/statoutput.cc
  src/sst/core/statapi/statoutput.h
  src/sst/core/statapi/statoutputcsv.cc
  src/sst/core/statapi/statoutputhdf5.cc
  src/sst/core/statapi/statoutputjson.cc
  src/sst/core/statapi/statoutputtxt.cc
  src/sst/core/statapi/statoutputtxt.h
  src/sst/core/statapi/statuniquecount.h
  src/sst/core/testElements/coreTest_Serialization.cc
  src/sst/core/util/Makefile.inc
  src/sst/core/util/filesystem.cc
  src/sst/core/util/filesystem.h
  tests/refFiles/test_Profiling_event_component.out
  tests/refFiles/test_Profiling_event_global.out
  tests/refFiles/test_Profiling_event_subcomponent.out
  tests/refFiles/test_Profiling_event_type.out
  tests/testsuite_default_Checkpoint.py
  tests/testsuite_default_Serialization.py
  tests/testsuite_default_config_input_output.py
  tests/testsuite_default_profiling.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1267 Fix #1262 by specifying intended base class
  src/sst/core/testingframework/test_engine_unittest.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1269 Add include guard to sst_config.h
  configure.ac
Labels: Enhancement, SST-BuildSystem, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1272 Fixes for HDF5 stat output and test
  src/sst/core/statapi/statoutputhdf5.cc
  tests/refFiles/test_StatisticsComponent_basic_h5.out
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1251 Reformat long TimeVortex string messages to be split across lines.
  src/sst/core/impl/timevortex/timeVortexBinnedMap.cc
  src/sst/core/impl/timevortex/timeVortexPQ.cc
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1254 Add [[noreturn]] to non-virtual functions which do not return
  src/sst/core/baseComponent.h
  src/sst/core/factory.h
  src/sst/core/serialization/serializable_base.h
  src/sst/core/sstconfigtool.cc
  src/sst/core/statapi/statengine.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1276 Added WatchPoints and enabled them in SimpleDebug
  .clang-format
  src/sst/core/Makefile.am
  src/sst/core/baseComponent.cc
  src/sst/core/baseComponent.h
  src/sst/core/clock.cc
  src/sst/core/impl/interactive/simpleDebug.cc
  src/sst/core/impl/interactive/simpleDebug.h
  src/sst/core/link.cc
  src/sst/core/link.h
  src/sst/core/serialization/impl/mapper.cc
  src/sst/core/serialization/impl/mapper.h
  src/sst/core/serialization/objectMap.h
  src/sst/core/serialization/objectMapDeferred.h
  src/sst/core/serialization/serializer.cc
  src/sst/core/serialization/serializer.h
  src/sst/core/ssthandler.h
  src/sst/core/testElements/coreTest_SubComponent.cc
  src/sst/core/testElements/coreTest_SubComponent.h
  src/sst/core/watchPoint.cc
  src/sst/core/watchPoint.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1278 Fix config output
  src/sst/core/cfgoutput/pythonConfigOutput.cc
  src/sst/core/cfgoutput/pythonConfigOutput.h
  src/sst/core/config.cc
  src/sst/core/configGraph.cc
  src/sst/core/model/python/pymodel.cc
  src/sst/core/model/python/pymodel_comp.cc
  tests/subcomponent_tests/refFiles/test_sc_2u.out
  tests/subcomponent_tests/refFiles/test_sc_2u2u.out
  tests/subcomponent_tests/test_sc_2u.py
  tests/subcomponent_tests/test_sc_2u2u.py
  tests/test_ParamComponent.py
Labels: Bug, SST-Core, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS
