Repository sstsimulator/sst-core, pull requests merged in 2025-08, with the labels that each got.

#1394 Convert array sizes in one place, flagging errors; cleanup packing code
  src/sst/core/Makefile.am
  src/sst/core/serialization/impl/get_array_size.h
  src/sst/core/serialization/impl/packer.cc
  src/sst/core/serialization/impl/packer.h
  src/sst/core/serialization/impl/serialize_array.h
  src/sst/core/serialization/impl/serialize_utility.h
  src/sst/core/serialization/impl/sizer.h
  src/sst/core/serialization/impl/unpacker.h
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1397 Fix for Issue #1391: Disambiguates subcomponent object names in Python config output and reorganizes the link construction
  src/sst/core/cfgoutput/pythonConfigOutput.cc
  src/sst/core/cfgoutput/pythonConfigOutput.h
Labels: Bug, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1383 Remove existing and prevent future trailing whitespace
  .clang-format
  .git-blame-ignore-revs
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  config/acx_mpi.m4
  config/sst_check_fpic.m4
  config/sst_check_hdf5.m4
  config/sst_check_libz.m4
  config/sst_check_mempool.m4
  config/sst_check_os.m4
  config/sst_check_picky.m4
  config/sst_check_python.m4
  config/sst_enable_perf_tracking.m4
  doc/Doxyfile.in
  experimental/cmake_configure_files/sst_config.h.in
  experimental/cmake_configure_files/sstsimulator.conf.in
  scripts/clang-format-test.sh
  scripts/format-diff
  scripts/sst-snippets.py
  src/sst/core/impl/partitioners/Makefile.inc
  src/sst/core/testingframework/sst_unittest.py
  src/sst/core/testingframework/sst_unittest_support.py
  tests/subcomponent_tests/test_sc_2u.py
  tests/subcomponent_tests/test_sc_2u2u.py
  tests/test_Component_createStats.py
  tests/test_Component_enableAllStats.py
  tests/test_Component_setStats.py
  tests/test_MessageMesh.py
  tests/test_ParallelLoad.py
  tests/test_PortModule.py
  tests/testsuite_default_Checkpoint.py
  tests/testsuite_default_Output.py
  tests/testsuite_default_PerfComponent.py
  tests/testsuite_default_PortModule.py
  tests/testsuite_default_RealTime.py
  tests/testsuite_default_StatisticsComponent.py
  tests/testsuite_default_TimingInfo.py
  tests/testsuite_default_UnitAlgebra.py
  tests/testsuite_default_config_input_output.py
  tests/testsuite_default_partitioner.py
  tests/testsuite_default_profiling.py
  tests/testsuite_default_sstinfo.py
  tests/testsuite_testengine_testing.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1405 Reorganize code into regions in main()
  src/sst/core/Makefile.am
  src/sst/core/cfgoutput/jsonConfigOutput.cc
  src/sst/core/cfgoutput/pythonConfigOutput.cc
  src/sst/core/config.cc
  src/sst/core/config.h
  src/sst/core/factory.cc
  src/sst/core/factory.h
  src/sst/core/main.cc
  src/sst/core/simulation.cc
  src/sst/core/simulation_impl.h
  src/sst/core/sst_mpi.cc
  src/sst/core/sst_mpi.h
  src/sst/core/timingOutput.cc
  src/sst/core/timingOutput.h
  src/sst/core/util/Makefile.inc
  src/sst/core/util/basicPerf.cc
  src/sst/core/util/basicPerf.h
Labels: Enhancement, AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS

#1408 Skip hdf5 tests for parallel runs for now
  src/sst/core/util/basicPerf.h
  tests/testsuite_default_StatisticsComponent.py
Labels: AT: CLANG-FORMAT PASS, AT: CMAKE-FORMAT PASS
